// ===== 四级核心词库（首批 100 个高频词） =====
const WORDS = [
    { id: "w001", word: "abandon", phonetic: "/əˈbændən/", pos: "v.", meaning: "放弃；抛弃", example: "He had to abandon his plan." },
    { id: "w002", word: "ability", phonetic: "/əˈbɪləti/", pos: "n.", meaning: "能力；才能", example: "She has the ability to lead." },
    { id: "w003", word: "abroad", phonetic: "/əˈbrɔːd/", pos: "adv.", meaning: "在国外；到国外", example: "He dreams of studying abroad." },
    { id: "w004", word: "absence", phonetic: "/ˈæbsəns/", pos: "n.", meaning: "缺席；不在", example: "His absence was noticed." },
    { id: "w005", word: "absolute", phonetic: "/ˈæbsəluːt/", pos: "adj.", meaning: "绝对的；完全的", example: "I have absolute trust in her." },
    { id: "w006", word: "absorb", phonetic: "/əbˈzɔːrb/", pos: "v.", meaning: "吸收；吸引", example: "Plants absorb sunlight." },
    { id: "w007", word: "abstract", phonetic: "/ˈæbstrækt/", pos: "adj.", meaning: "抽象的；摘要", example: "The idea is too abstract." },
    { id: "w008", word: "abundant", phonetic: "/əˈbʌndənt/", pos: "adj.", meaning: "丰富的；充裕的", example: "The region has abundant resources." },
    { id: "w009", word: "academic", phonetic: "/ˌækəˈdemɪk/", pos: "adj.", meaning: "学术的；学院的", example: "She has high academic achievements." },
    { id: "w010", word: "accelerate", phonetic: "/əkˈseləreɪt/", pos: "v.", meaning: "加速；加快", example: "The car accelerated quickly." },
    { id: "w011", word: "access", phonetic: "/ˈækses/", pos: "n.", meaning: "进入；通道；访问", example: "Students have access to the library." },
    { id: "w012", word: "accompany", phonetic: "/əˈkʌmpəni/", pos: "v.", meaning: "陪伴；伴随", example: "She accompanied me to the station." },
    { id: "w013", word: "accomplish", phonetic: "/əˈkɑːmplɪʃ/", pos: "v.", meaning: "完成；实现", example: "We accomplished our mission." },
    { id: "w014", word: "account", phonetic: "/əˈkaʊnt/", pos: "n.", meaning: "账户；说明", example: "I opened a bank account." },
    { id: "w015", word: "accurate", phonetic: "/ˈækjərət/", pos: "adj.", meaning: "准确的；精确的", example: "The data is accurate." },
    { id: "w016", word: "achieve", phonetic: "/əˈtʃiːv/", pos: "v.", meaning: "达到；取得", example: "He achieved his goal." },
    { id: "w017", word: "acknowledge", phonetic: "/əkˈnɑːlɪdʒ/", pos: "v.", meaning: "承认；确认", example: "She acknowledged her mistake." },
    { id: "w018", word: "acquire", phonetic: "/əˈkwaɪər/", pos: "v.", meaning: "获得；习得", example: "It's hard to acquire a new language." },
    { id: "w019", word: "adapt", phonetic: "/əˈdæpt/", pos: "v.", meaning: "适应；改编", example: "You need to adapt to the new environment." },
    { id: "w020", word: "adequate", phonetic: "/ˈædɪkwət/", pos: "adj.", meaning: "足够的；适当的", example: "The supply is adequate for our needs." },
    { id: "w021", word: "adjust", phonetic: "/əˈdʒʌst/", pos: "v.", meaning: "调整；适应", example: "I need to adjust the volume." },
    { id: "w022", word: "administration", phonetic: "/ədˌmɪnɪˈstreɪʃn/", pos: "n.", meaning: "管理；行政", example: "The administration made new rules." },
    { id: "w023", word: "admission", phonetic: "/ədˈmɪʃn/", pos: "n.", meaning: "准入；承认", example: "He gained admission to the university." },
    { id: "w024", word: "adopt", phonetic: "/əˈdɑːpt/", pos: "v.", meaning: "采用；收养", example: "They decided to adopt the new method." },
    { id: "w025", word: "advance", phonetic: "/ədˈvæns/", pos: "v.", meaning: "前进；提前", example: "Technology continues to advance." },
    { id: "w026", word: "advantage", phonetic: "/ədˈvæntɪdʒ/", pos: "n.", meaning: "优势；有利条件", example: "Being tall is an advantage in basketball." },
    { id: "w027", word: "advertise", phonetic: "/ˈædvərtaɪz/", pos: "v.", meaning: "做广告；宣传", example: "They advertise on social media." },
    { id: "w028", word: "affair", phonetic: "/əˈfer/", pos: "n.", meaning: "事务；事件", example: "It's a private affair." },
    { id: "w029", word: "affect", phonetic: "/əˈfekt/", pos: "v.", meaning: "影响；感染", example: "The weather affects our mood." },
    { id: "w030", word: "afford", phonetic: "/əˈfɔːrd/", pos: "v.", meaning: "负担得起；提供", example: "I can't afford a new car." },
    { id: "w031", word: "aggressive", phonetic: "/əˈɡresɪv/", pos: "adj.", meaning: "侵略的；好斗的", example: "The company has an aggressive strategy." },
    { id: "w032", word: "agreement", phonetic: "/əˈɡriːmənt/", pos: "n.", meaning: "协议；一致", example: "They reached an agreement." },
    { id: "w033", word: "aid", phonetic: "/eɪd/", pos: "n.", meaning: "援助；帮助", example: "They provided aid to the victims." },
    { id: "w034", word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", pos: "n.", meaning: "替代选择；备选方案", example: "Is there an alternative to this plan?" },
    { id: "w035", word: "amaze", phonetic: "/əˈmeɪz/", pos: "v.", meaning: "使惊奇；使惊愕", example: "His performance amazed everyone." },
    { id: "w036", word: "amount", phonetic: "/əˈmaʊnt/", pos: "n.", meaning: "数量；总额", example: "A large amount of money was spent." },
    { id: "w037", word: "analyze", phonetic: "/ˈænəlaɪz/", pos: "v.", meaning: "分析；解析", example: "We need to analyze the data." },
    { id: "w038", word: "annual", phonetic: "/ˈænjuəl/", pos: "adj.", meaning: "年度的；每年的", example: "The annual meeting will be held next week." },
    { id: "w039", word: "anxiety", phonetic: "/æŋˈzaɪəti/", pos: "n.", meaning: "焦虑；忧虑", example: "She felt anxiety before the exam." },
    { id: "w040", word: "apparent", phonetic: "/əˈpærənt/", pos: "adj.", meaning: "明显的；表面上的", example: "It became apparent that he was wrong." },
    { id: "w041", word: "appeal", phonetic: "/əˈpiːl/", pos: "v.", meaning: "呼吁；吸引；上诉", example: "The idea appeals to young people." },
    { id: "w042", word: "appetite", phonetic: "/ˈæpɪtaɪt/", pos: "n.", meaning: "食欲；胃口", example: "Exercise gave me a good appetite." },
    { id: "w043", word: "apply", phonetic: "/əˈplaɪ/", pos: "v.", meaning: "申请；应用", example: "I applied for a job at the company." },
    { id: "w044", word: "appreciate", phonetic: "/əˈpriːʃieɪt/", pos: "v.", meaning: "欣赏；感激；领会", example: "I appreciate your help." },
    { id: "w045", word: "approach", phonetic: "/əˈproʊtʃ/", pos: "v.", meaning: "接近；方法", example: "Winter is approaching." },
    { id: "w046", word: "appropriate", phonetic: "/əˈproʊpriət/", pos: "adj.", meaning: "适当的；合适的", example: "This isn't the appropriate time." },
    { id: "w047", word: "arise", phonetic: "/əˈraɪz/", pos: "v.", meaning: "出现；产生", example: "Problems may arise unexpectedly." },
    { id: "w048", word: "artificial", phonetic: "/ˌɑːrtɪˈfɪʃl/", pos: "adj.", meaning: "人工的；人造的", example: "Artificial intelligence is evolving rapidly." },
    { id: "w049", word: "aspect", phonetic: "/ˈæspekt/", pos: "n.", meaning: "方面；层面", example: "We considered every aspect of the problem." },
    { id: "w050", word: "assemble", phonetic: "/əˈsembl/", pos: "v.", meaning: "集合；组装", example: "The students assembled in the hall." },
    { id: "w051", word: "assess", phonetic: "/əˈses/", pos: "v.", meaning: "评估；评定", example: "The teacher assessed the students' work." },
    { id: "w052", word: "assign", phonetic: "/əˈsaɪn/", pos: "v.", meaning: "分配；指派", example: "The boss assigned me a new task." },
    { id: "w053", word: "assist", phonetic: "/əˈsɪst/", pos: "v.", meaning: "帮助；协助", example: "She assisted me with my homework." },
    { id: "w054", word: "associate", phonetic: "/əˈsoʊʃieɪt/", pos: "v.", meaning: "联系；关联", example: "People often associate red with danger." },
    { id: "w055", word: "assume", phonetic: "/əˈsuːm/", pos: "v.", meaning: "假设；承担", example: "I assume you know the answer." },
    { id: "w056", word: "atmosphere", phonetic: "/ˈætməsfɪr/", pos: "n.", meaning: "气氛；大气", example: "The restaurant has a cozy atmosphere." },
    { id: "w057", word: "attach", phonetic: "/əˈtætʃ/", pos: "v.", meaning: "附上；连接", example: "Please attach the file to the email." },
    { id: "w058", word: "attempt", phonetic: "/əˈtempt/", pos: "v.", meaning: "尝试；企图", example: "He attempted to break the record." },
    { id: "w059", word: "attend", phonetic: "/əˈtend/", pos: "v.", meaning: "参加；出席", example: "Many people attended the meeting." },
    { id: "w060", word: "attitude", phonetic: "/ˈætɪtuːd/", pos: "n.", meaning: "态度；看法", example: "A positive attitude helps a lot." },
    { id: "w061", word: "attract", phonetic: "/əˈtrækt/", pos: "v.", meaning: "吸引；引起", example: "The exhibition attracted many visitors." },
    { id: "w062", word: "authority", phonetic: "/əˈθɔːrəti/", pos: "n.", meaning: "权威；当局", example: "The authorities are investigating the case." },
    { id: "w063", word: "available", phonetic: "/əˈveɪləbl/", pos: "adj.", meaning: "可用的；有空的", example: "Is this seat available?" },
    { id: "w064", word: "average", phonetic: "/ˈævərɪdʒ/", pos: "adj.", meaning: "平均的；普通的", example: "The average temperature is 20 degrees." },
    { id: "w065", word: "avoid", phonetic: "/əˈvɔɪd/", pos: "v.", meaning: "避免；避开", example: "You should avoid making the same mistake." },
    { id: "w066", word: "award", phonetic: "/əˈwɔːrd/", pos: "n.", meaning: "奖励；奖品", example: "She won an award for her essay." },
    { id: "w067", word: "aware", phonetic: "/əˈwer/", pos: "adj.", meaning: "意识到的；知道的", example: "I'm aware of the risks." },
    { id: "w068", word: "barrier", phonetic: "/ˈbæriər/", pos: "n.", meaning: "障碍；屏障", example: "Language can be a barrier." },
    { id: "w069", word: "benefit", phonetic: "/ˈbenɪfɪt/", pos: "n.", meaning: "好处；利益", example: "Exercise has many health benefits." },
    { id: "w070", word: "budget", phonetic: "/ˈbʌdʒɪt/", pos: "n.", meaning: "预算", example: "We need to stick to our budget." },
    { id: "w071", word: "burden", phonetic: "/ˈbɜːrdn/", pos: "n.", meaning: "负担；重担", example: "The debt was a heavy burden." },
    { id: "w072", word: "campaign", phonetic: "/kæmˈpeɪn/", pos: "n.", meaning: "运动；活动；战役", example: "They launched a new marketing campaign." },
    { id: "w073", word: "capable", phonetic: "/ˈkeɪpəbl/", pos: "adj.", meaning: "有能力的；能干的", example: "She is a capable leader." },
    { id: "w074", word: "capacity", phonetic: "/kəˈpæsəti/", pos: "n.", meaning: "能力；容量", example: "The hall has a capacity of 500." },
    { id: "w075", word: "capture", phonetic: "/ˈkæptʃər/", pos: "v.", meaning: "捕获；俘获", example: "The police captured the suspect." },
    { id: "w076", word: "career", phonetic: "/kəˈrɪr/", pos: "n.", meaning: "职业；生涯", example: "She chose teaching as her career." },
    { id: "w077", word: "challenge", phonetic: "/ˈtʃælɪndʒ/", pos: "n.", meaning: "挑战；困难", example: "This project is a real challenge." },
    { id: "w078", word: "characteristic", phonetic: "/ˌkærəktəˈrɪstɪk/", pos: "n.", meaning: "特征；特点", example: "Patience is a key characteristic of a teacher." },
    { id: "w079", word: "circumstance", phonetic: "/ˈsɜːrkəmstæns/", pos: "n.", meaning: "环境；情况", example: "Under no circumstances should you lie." },
    { id: "w080", word: "claim", phonetic: "/kleɪm/", pos: "v.", meaning: "声称；要求", example: "He claims to be innocent." },
    { id: "w081", word: "colleague", phonetic: "/ˈkɑːliːɡ/", pos: "n.", meaning: "同事；同僚", example: "I discussed the issue with my colleagues." },
    { id: "w082", word: "combine", phonetic: "/kəmˈbaɪn/", pos: "v.", meaning: "结合；联合", example: "We should combine our efforts." },
    { id: "w083", word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", pos: "v.", meaning: "交流；沟通", example: "We communicate via email." },
    { id: "w084", word: "community", phonetic: "/kəˈmjuːnəti/", pos: "n.", meaning: "社区；团体", example: "The local community supports the project." },
    { id: "w085", word: "compare", phonetic: "/kəmˈper/", pos: "v.", meaning: "比较；对比", example: "Don't compare yourself with others." },
    { id: "w086", word: "compete", phonetic: "/kəmˈpiːt/", pos: "v.", meaning: "竞争；比赛", example: "They compete for the championship." },
    { id: "w087", word: "complaint", phonetic: "/kəmˈpleɪnt/", pos: "n.", meaning: "抱怨；投诉", example: "We received a complaint from a customer." },
    { id: "w088", word: "complex", phonetic: "/kəmˈpleks/", pos: "adj.", meaning: "复杂的；难懂的", example: "The problem is very complex." },
    { id: "w089", word: "concentrate", phonetic: "/ˈkɑːnsntreɪt/", pos: "v.", meaning: "集中；专注", example: "I can't concentrate with this noise." },
    { id: "w090", word: "concept", phonetic: "/ˈkɑːnsept/", pos: "n.", meaning: "概念；观念", example: "It's a difficult concept to understand." },
    { id: "w091", word: "concern", phonetic: "/kənˈsɜːrn/", pos: "n.", meaning: "关心；担忧", example: "Environmental concern is growing." },
    { id: "w092", word: "conduct", phonetic: "/kənˈdʌkt/", pos: "v.", meaning: "进行；指挥", example: "They conducted an experiment." },
    { id: "w093", word: "confidence", phonetic: "/ˈkɑːnfɪdəns/", pos: "n.", meaning: "信心；信任", example: "She has confidence in her abilities." },
    { id: "w094", word: "confirm", phonetic: "/kənˈfɜːrm/", pos: "v.", meaning: "确认；证实", example: "Can you confirm the date?" },
    { id: "w095", word: "consequence", phonetic: "/ˈkɑːnsɪkwens/", pos: "n.", meaning: "结果；后果", example: "Think about the consequences of your actions." },
    { id: "w096", word: "conserve", phonetic: "/kənˈsɜːrv/", pos: "v.", meaning: "保存；节约", example: "We should conserve energy." },
    { id: "w097", word: "consider", phonetic: "/kənˈsɪdər/", pos: "v.", meaning: "考虑；认为", example: "Please consider my suggestion." },
    { id: "w098", word: "consist", phonetic: "/kənˈsɪst/", pos: "v.", meaning: "由…组成；在于", example: "The team consists of five members." },
    { id: "w099", word: "constitution", phonetic: "/ˌkɑːnstɪˈtuːʃn/", pos: "n.", meaning: "宪法；构成", example: "It is protected by the constitution." },
    { id: "w100", word: "construct", phonetic: "/kənˈstrʌkt/", pos: "v.", meaning: "建造；构建", example: "They constructed a new bridge." }
];

// ===== 四级语法知识点 =====
const GRAMMAR = [
    {
        id: "g01",
        category: "时态",
        title: "一般现在时",
        content: "表示经常发生的动作、客观事实或普遍真理。主语为第三人称单数时，动词加 -s 或 -es。",
        example: "The sun rises in the east.（太阳从东方升起。）"
    },
    {
        id: "g02",
        category: "时态",
        title: "一般过去时",
        content: "表示过去某个时间发生的动作或状态。动词用过去式，常与 yesterday, last week, ago 等时间状语连用。",
        example: "I visited my grandparents last weekend.（我上周末去看了祖父母。）"
    },
    {
        id: "g03",
        category: "时态",
        title: "现在完成时",
        content: "表示过去发生的动作对现在造成的影响或持续到现在的状态。结构：have/has + 过去分词。",
        example: "She has lived here for ten years.（她已经在这里住了十年了。）"
    },
    {
        id: "g04",
        category: "时态",
        title: "过去完成时",
        content: "表示在过去某一时间之前已经完成的动作，即"过去的过去"。结构：had + 过去分词。",
        example: "By the time I arrived, the train had already left.（我到的时候，火车已经开走了。）"
    },
    {
        id: "g05",
        category: "时态",
        title: "将来时（will / be going to）",
        content: "will 表示临时决定或预测；be going to 表示计划好的打算或有迹象要发生的事。",
        example: "Look at those clouds! It is going to rain.（看那些云！要下雨了。）"
    },
    {
        id: "g06",
        category: "语态",
        title: "被动语态",
        content: "强调动作的承受者而非执行者。结构：be + 过去分词。不同时态对应 be 动词的不同形式。",
        example: "This book was written by Lu Xun.（这本书是鲁迅写的。）"
    },
    {
        id: "g07",
        category: "从句",
        title: "定语从句",
        content: "修饰名词或代词的从句。关系代词有 who(人), which(物), that(人物均可), whose(所属)。限定性定语从句不可省略。",
        example: "The girl who is sitting there is my sister.（坐在那边的女孩是我妹妹。）"
    },
    {
        id: "g08",
        category: "从句",
        title: "名词性从句",
        content: "在句中充当主语、宾语、表语或同位语的从句。常由 that, whether, if 或疑问词引导。",
        example: "What he said surprised everyone.（他说的话让所有人惊讶。）"
    },
    {
        id: "g09",
        category: "从句",
        title: "状语从句",
        content: "修饰主句的动词、形容词或副词，表示时间、原因、条件、让步、目的等。由 when, because, if, although, so that 等引导。",
        example: "Although it was raining, he went out.（虽然在下雨，他还是出去了。）"
    },
    {
        id: "g10",
        category: "虚拟语气",
        title: "条件虚拟（if 从句）",
        content: "表示与事实相反的假设。与现在相反：If + 过去式, would + 动词原形。与过去相反：If + had + 过去分词, would have + 过去分词。",
        example: "If I were you, I would take the job.（如果我是你，我会接受那份工作。）"
    },
    {
        id: "g11",
        category: "虚拟语气",
        title: "should + 动词原形",
        content: "在 suggest, insist, recommend, demand 等表示建议/命令/要求的动词后的 that 从句中，谓语用 should + 动词原形（should 可省略）。",
        example: "The teacher suggested that we (should) review the lesson.（老师建议我们复习这节课。）"
    },
    {
        id: "g12",
        category: "非谓语动词",
        title: "动词不定式（to do）",
        content: "由 to + 动词原形构成，可在句中充当主语、宾语、定语、状语等。常表目的或未发生的动作。",
        example: "I came here to see you.（我来这里是为了见你。）"
    },
    {
        id: "g13",
        category: "非谓语动词",
        title: "动名词（-ing 作名词）",
        content: "动词的 -ing 形式具有名词功能，可充当主语、宾语等。常表一般性、习惯性的动作。",
        example: "Swimming is good for your health.（游泳对健康有益。）"
    },
    {
        id: "g14",
        category: "非谓语动词",
        title: "分词（-ing / -ed）",
        content: "现在分词（-ing）表主动/进行；过去分词（-ed）表被动/完成。可作定语、状语、补语。",
        example: "The boy standing there is my brother.（站在那边的男孩是我弟弟。）"
    },
    {
        id: "g15",
        category: "倒装",
        title: "部分倒装",
        content: "否定词（never, hardly, not until 等）置于句首时，主语和助动词倒装。Only + 状语位于句首时也需要倒装。",
        example: "Never have I seen such a beautiful sunset.（我从未见过这么美的日落。）"
    }
];
